"""Selection domain boundary for the product rewrite."""

from .indicators import compute_kdj
from .preselect import (
    LegacyLiquidityPoolPort,
    LegacyMarketDataPort,
    LegacyMarketPreparationPort,
    LegacyPickDatePort,
    LegacyPreselectExecutionPort,
    LegacyStrategyFormulaFactoryPort,
    LegacyStrategySelectorPort,
    LegacyWarmupBarsPort,
    LiquidityPoolPort,
    MarketDataPort,
    MarketPreparationPort,
    PickDatePort,
    ProductCsvMarketDataPort,
    ProductLiquidityPoolPort,
    ProductMarketPreparationPort,
    ProductPickDatePort,
    ProductStrategySelectorPort,
    ProductWarmupBarsPort,
    PreselectExecutionSettings,
    PreselectExecutionPort,
    PreselectParameters,
    PreselectResult,
    PreselectService,
    SelectionCandidate,
    StrategyFormulaFactoryPort,
    StrategySelectorPort,
    WarmupBarsPort,
)

__all__ = [
    "compute_kdj",
    "LegacyLiquidityPoolPort",
    "LegacyMarketDataPort",
    "LegacyMarketPreparationPort",
    "LegacyPickDatePort",
    "LegacyPreselectExecutionPort",
    "LegacyStrategyFormulaFactoryPort",
    "LegacyStrategySelectorPort",
    "LegacyWarmupBarsPort",
    "LiquidityPoolPort",
    "MarketDataPort",
    "MarketPreparationPort",
    "PickDatePort",
    "ProductCsvMarketDataPort",
    "ProductLiquidityPoolPort",
    "ProductMarketPreparationPort",
    "ProductPickDatePort",
    "ProductStrategySelectorPort",
    "ProductWarmupBarsPort",
    "PreselectExecutionSettings",
    "PreselectExecutionPort",
    "PreselectParameters",
    "PreselectResult",
    "PreselectService",
    "SelectionCandidate",
    "StrategyFormulaFactoryPort",
    "StrategySelectorPort",
    "WarmupBarsPort",
]
